# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/environment.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x61pi/environment.proto\x12\tcollector\")\n\x10GetStatesRequest\x12\x15\n\rinstance_name\x18\x01 \x01(\t\"$\n\x11GetStatesResponse\x12\x0f\n\x07metrics\x18\x01 \x03(\x02\"\x85\x01\n\x13\x41pplyActionsRequest\x12\x15\n\rinstance_name\x18\x01 \x01(\t\x12\x32\n\x05knobs\x18\x02 \x01(\x0b\x32#.collector.ApplyActionsRequest.Knob\x1a#\n\x04Knob\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02\"\x16\n\x14\x41pplyActionsResponse\"0\n\x17GetRewardMetricsRequest\x12\x15\n\rinstance_name\x18\x01 \x01(\t\"8\n\x18GetRewardMetricsResponse\x12\x0f\n\x07latency\x18\x01 \x01(\x02\x12\x0b\n\x03tps\x18\x02 \x01(\x02\"/\n\x16InitEnvironmentRequest\x12\x15\n\rinstance_name\x18\x01 \x01(\t\"\x19\n\x17InitEnvironmentResponse2\xdd\x02\n\x0b\x45nvironment\x12\x46\n\tGetStates\x12\x1b.collector.GetStatesRequest\x1a\x1c.collector.GetStatesResponse\x12O\n\x0c\x41pplyActions\x12\x1e.collector.ApplyActionsRequest\x1a\x1f.collector.ApplyActionsResponse\x12[\n\x10GetRewardMetrics\x12\".collector.GetRewardMetricsRequest\x1a#.collector.GetRewardMetricsResponse\x12X\n\x0fInitEnvironment\x12!.collector.InitEnvironmentRequest\x1a\".collector.InitEnvironmentResponseB\x08Z\x06pkg/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.environment_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\006pkg/pb'
  _globals['_GETSTATESREQUEST']._serialized_start=36
  _globals['_GETSTATESREQUEST']._serialized_end=77
  _globals['_GETSTATESRESPONSE']._serialized_start=79
  _globals['_GETSTATESRESPONSE']._serialized_end=115
  _globals['_APPLYACTIONSREQUEST']._serialized_start=118
  _globals['_APPLYACTIONSREQUEST']._serialized_end=251
  _globals['_APPLYACTIONSREQUEST_KNOB']._serialized_start=216
  _globals['_APPLYACTIONSREQUEST_KNOB']._serialized_end=251
  _globals['_APPLYACTIONSRESPONSE']._serialized_start=253
  _globals['_APPLYACTIONSRESPONSE']._serialized_end=275
  _globals['_GETREWARDMETRICSREQUEST']._serialized_start=277
  _globals['_GETREWARDMETRICSREQUEST']._serialized_end=325
  _globals['_GETREWARDMETRICSRESPONSE']._serialized_start=327
  _globals['_GETREWARDMETRICSRESPONSE']._serialized_end=383
  _globals['_INITENVIRONMENTREQUEST']._serialized_start=385
  _globals['_INITENVIRONMENTREQUEST']._serialized_end=432
  _globals['_INITENVIRONMENTRESPONSE']._serialized_start=434
  _globals['_INITENVIRONMENTRESPONSE']._serialized_end=459
  _globals['_ENVIRONMENT']._serialized_start=462
  _globals['_ENVIRONMENT']._serialized_end=811
# @@protoc_insertion_point(module_scope)
